// GAMERS locations

export const locations = [
	{
		id: "1.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KATIKEKILE",
		village: "NAKOMOL WARET ",
		healthFacilities: "Kosiroi HF",
	},
	{
		id: "2.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KATIKEKILE",
		village: "NAPAO ACHOKON ",
		healthFacilities: "Kosiroi HF & Kalemungole",
	},
	{
		id: "3.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KATIKEKILE",
		village: "KOSIROI ",
		healthFacilities: "Kosiroi HF",
	},
	{
		id: "4.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KATIKEKILE",
		village: "",
		healthFacilities: "Kalemungole",
	},
	{
		id: "5.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KATIKEKILE",
		village: "KATIKEKILE ",
		healthFacilities: "Kosiroi HF",
	},
	{
		id: "6.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KATIKEKILE",
		village: "NAKONYEN ",
		healthFacilities: "Kalemungole",
	},
	{
		id: "7.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KODONYO",
		village: "TIKOKIN",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "8.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KODONYO",
		village: "NAMICHOT",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "9.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KODONYO",
		village: "LOMORU ARENGAN",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "10.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KODONYO",
		village: "LOMUNYEN KIPURAT",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "11.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KODONYO",
		village: "BELLEMIT",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "12.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "KODONYO",
		village: "OGOLOT",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "13.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "LOYARABOTH",
		village: "NARACHUCH",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "14.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "LOYARABOTH",
		village: "ALAMAE ",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "15.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "LOYARABOTH",
		village: "LOKILES ",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "16.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NAKWANGA",
		village: "NAKWANGA",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "17.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NAKWANGA",
		village: "ADULEI",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "18.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NAKWANGA",
		village: "NATEBA KALEJOI",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "19.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NAKWANGA",
		village: "LOPELIPEL ",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "20.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NAKWANGA",
		village: "KAREAPETUKO ",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "21.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NAKWANGA",
		village: "NAUT",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "22.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NATUMKALE",
		village: "LOMELAN ",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "23.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NATUMKALE",
		village: "MORUKERIS",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "24.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NATUMKALE",
		village: "DIDI",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "25.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NATUMKALE",
		village: "MUTIA ",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "26.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "NATUMKALE",
		village: "LOTORONGOR",
		healthFacilities: "Lopelipel HCII",
	},
	{
		id: "27.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "TAPAC",
		village: "LOMUDITA A",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "28.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "TAPAC",
		village: "SEGET ",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "29.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "TAPAC",
		village: "AKARIWON",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "30.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "TAPAC",
		village: "LONYILIK ",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "31.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "TAPAC",
		village: "NAPAK-AKIMUL",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "32.0",
		county: "MATHENIKO",
		subCounty: "TAPAC",
		parishName: "TAPAC",
		village: "TIMINGOROK A",
		healthFacilities: "Tapac HCIII",
	},
	{
		id: "33.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "KAKINGOL",
		village: "NAMEJA ",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "34.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "KAKINGOL",
		village: "NAKODET ",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "35.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "KAKINGOL",
		village: "NAKWANGA",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "36.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "KAKINGOL",
		village: "OMUTUK ",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "37.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "KAKINGOL",
		village: "NACHOCHIA",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "38.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "KAKINGOL",
		village: "LONGUREPE ",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "39.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "KAKINGOL",
		village: "NAROO",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "40.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "NABUIN",
		healthFacilities: "Nakapelimen HCIII & Prisons ",
	},
	{
		id: "41.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "NAMORUTOMEI",
		healthFacilities: "Nakapelimen HCIII & Prisons ",
	},
	{
		id: "42.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "NAKACHAT",
		healthFacilities: "Nakapelimen HCIII & Prisons ",
	},
	{
		id: "43.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "NADUKON",
		healthFacilities: "Nakapelimen HCIII & Prisons ",
	},
	{
		id: "44.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "AROWOESE",
		healthFacilities: "Nakapelimen HCIII & Prisons ",
	},
	{
		id: "45.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "SINGILA ",
		healthFacilities: "Nakapelimen HCIII & Prisons ",
	},
	{
		id: "46.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "",
		healthFacilities: "MRRH",
	},
	{
		id: "47.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "LIA",
		village: "",
		healthFacilities: "MRHH",
	},
	{
		id: "48.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "MUSAS",
		village: "AKIMABUL ",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "49.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "MUSAS",
		village: "ACHUKUL",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "50.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "MUSAS",
		village: "SOGOLOMONG",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "51.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "MUSAS",
		village: "LOKUTAKORI",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "52.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "MUSAS",
		village: "NAKAMICHURA",
		healthFacilities: "kodoyo HF",
	},
	{
		id: "53.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "ARENGECHOTO",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "54.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "KAITIRWA",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "55.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "MORUKEKOSOWAN",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "56.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "LOPONG",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "57.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "NARENGENYA",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "58.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "GRAZING AREA",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "59.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "NATEDENKENYIT",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "60.0",
		county: "MATHENIKO",
		subCounty: "KATIKEKILE",
		parishName: "NARENGENYA",
		village: "KAABONG",
		healthFacilities: "Kakingol HCIII",
	},
	{
		id: "61.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "ACHERER  (Lotirir)",
		village: "ATEDEOI ",
		healthFacilities: "Acherere HCII",
	},
	{
		id: "63.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "ACHERER  (Lotirir)",
		village: "SIMON",
		healthFacilities: "Acherere HCII",
	},
	{
		id: "64.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "ACHERER  (Lotirir)",
		village: "KOPOE",
		healthFacilities: "Acherere HCII-VILL",
	},
	{
		id: "65.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "ACHERER  (Lotirir)",
		village: "ARENGEKEJU ",
		healthFacilities: "Acherere HCII",
	},
	{
		id: "66.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "KOMARET",
		village: "LORIKOKWA ",
		healthFacilities: "Nadunget",
	},
	{
		id: "67.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "KOMARET",
		village: "LODOOI ",
		healthFacilities: "Loputuk ",
	},
	{
		id: "68.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "KOMARET",
		village: "KOMARET",
		healthFacilities: "Nadunget ",
	},
	{
		id: "69.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "KOMARET",
		village: "ARECHEK",
		healthFacilities: "Nadunget ",
	},
	{
		id: "70.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "KOMARET",
		village: "",
		healthFacilities: "Nadunget",
	},
	{
		id: "71.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "KOMARET",
		village: "LONGOLEKI",
		healthFacilities: "Nadunget ",
	},
	{
		id: "72.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "KAMBIZI",
		healthFacilities: "Loputuk",
	},
	{
		id: "73.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "NACHOGOROM ",
		healthFacilities: "Loputuk",
	},
	{
		id: "74.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "LOKWAKWA",
		healthFacilities: "Loputuk",
	},
	{
		id: "75.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "APETAOI",
		healthFacilities: "Loputuk",
	},
	{
		id: "76.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "AWOROBU",
		healthFacilities: "Loputuk HCIII",
	},
	{
		id: "77.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "NADIKET",
		healthFacilities: "Loputuk HCIII",
	},
	{
		id: "78.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "NAGOROKIPI ",
		healthFacilities: "Loputu HCIII",
	},
	{
		id: "79.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "LOOI ",
		healthFacilities: "Loputuk  HCIII",
	},
	{
		id: "80.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "AKWAPUWA",
		healthFacilities: "Loputuk  HCIII",
	},
	{
		id: "81.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "KAMERA ",
		healthFacilities: "Loputuk  HCIII",
	},
	{
		id: "82.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "NATAPARAKOCUC ",
		healthFacilities: "Loputuk  HCIII",
	},
	{
		id: "83.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "KALOPWANYA",
		healthFacilities: "Loputuk  HCIII",
	},
	{
		id: "84.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "NASINYONOIT",
		healthFacilities: "Loputuk  HCIII",
	},
	{
		id: "85.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOPUTUK",
		village: "GRAZING AREA",
		healthFacilities: "Loputuk  HCIII",
	},
	{
		id: "86.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOTIRIR",
		village: "NACHUKA ",
		healthFacilities: "Lotirir HCII",
	},
	{
		id: "87.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOTIRIR",
		village: "NATARI",
		healthFacilities: "Lotirir HCII",
	},
	{
		id: "88.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOTIRIR",
		village: "NANGORIKIPI",
		healthFacilities: "Lotirir HCII",
	},
	{
		id: "89.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOTIRIR",
		village: "LORENGETELA ",
		healthFacilities: "Lotirir HCII",
	},
	{
		id: "90.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOTIRIR",
		village: "LOPUR ",
		healthFacilities: "Lotirir HCII",
	},
	{
		id: "91.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOTIRIR",
		village: "NAWANATAU",
		healthFacilities: "Lotirir HCII",
	},
	{
		id: "92.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "LOTIRIR",
		village: "NAMATWAE",
		healthFacilities: "Lotirir HCII",
	},
	{
		id: "93.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "LOKERIAUT ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "94.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "",
		healthFacilities: "Nadunget",
	},
	{
		id: "95.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "KOTARUK",
		healthFacilities: "Nadunget ",
	},
	{
		id: "96.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "LOLETEKIA",
		healthFacilities: "Nadunget ",
	},
	{
		id: "97.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "NACHUKA ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "98.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "NAKAPELIMEN ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "99.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "LOPUTIPUT ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "100.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "LOKILALA",
		healthFacilities: "Nadunget ",
	},
	{
		id: "101.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "LOKORIROT",
		healthFacilities: "Nadunget ",
	},
	{
		id: "102.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "NAKAMISTAE ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "103.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NADUNGET",
		village: "GRAZING AREA",
		healthFacilities: "Nadunget",
	},
	{
		id: "104.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "NACHORA ",
		healthFacilities: null,
	},
	{
		id: "105.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "NANGORIT ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "106.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "AWOIMUJU ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "107.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "KALOI",
		healthFacilities: "St pius Kidepo",
	},
	{
		id: "108.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "NAMIJMIJ",
		healthFacilities: "Nadunget & Dmos",
	},
	{
		id: "109.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "KATANGA ",
		healthFacilities: "Dmos Clinic HF",
	},
	{
		id: "110.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "KANAKOMOL ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "111.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "NABOKAT ",
		healthFacilities: "Nadunget  & Dmos ",
	},
	{
		id: "112.0",
		county: "MATHENIKO",
		subCounty: "NADUNGET",
		parishName: "NAITAKWAE",
		village: "NACHELE ",
		healthFacilities: "Nadunget ",
	},
	{
		id: "113.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "LOBUNET",
		village: "LOKITELAKAPIS",
		healthFacilities: null,
	},
	{
		id: "114.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "LOBUNET",
		village: "KADILAKENY",
		healthFacilities: "Rupa HF",
	},
	{
		id: "115.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "LOBUNET",
		village: "LONYASAN ",
		healthFacilities: "Rupa HF",
	},
	{
		id: "116.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "LOBUNET",
		village: "KOCHUNOI",
		healthFacilities: null,
	},
	{
		id: "117.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "LOBUNET",
		village: "LOKEMERKAPEL",
		healthFacilities: "Rupa HF",
	},
	{
		id: "118.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "LOBUNET",
		village: "LOOI ",
		healthFacilities: "Rupa HF",
	},
	{
		id: "119.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "LOBUNET",
		village: "KIDEPO-LOBUNEIT",
		healthFacilities: null,
	},
	{
		id: "120.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "PUPU",
		village: "NAOI",
		healthFacilities: "Rupa HF",
	},
	{
		id: "121.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "PUPU",
		village: "KALUKALET",
		healthFacilities: null,
	},
	{
		id: "122.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "PUPU",
		village: "",
		healthFacilities: null,
	},
	{
		id: "123.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "PUPU",
		village: "KWAMONG",
		healthFacilities: null,
	},
	{
		id: "124.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "PUPU",
		village: "KIDEPO PUPU",
		healthFacilities: null,
	},
	{
		id: "125.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "PUPU",
		village: "PUPU ",
		healthFacilities: null,
	},
	{
		id: "126.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "PUPU",
		village: "KANAKOL ",
		healthFacilities: null,
	},
	{
		id: "127.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "NAKADELI",
		village: "LOYAKARAMOE",
		healthFacilities: null,
	},
	{
		id: "128.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "NAKADELI",
		village: "KALOI",
		healthFacilities: null,
	},
	{
		id: "129.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "NAKADELI",
		village: "NATOPOJO",
		healthFacilities: null,
	},
	{
		id: "130.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "NAKADELI",
		village: "",
		healthFacilities: null,
	},
	{
		id: "131.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "NAKADELI",
		village: "NATUMUKASIKOU ",
		healthFacilities: "Dmos Clinic HF",
	},
	{
		id: "132.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "NAMOGORAT ",
		healthFacilities: null,
	},
	{
		id: "133.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "AKWAPUWA ",
		healthFacilities: null,
	},
	{
		id: "134.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "ATEDOI ",
		healthFacilities: null,
	},
	{
		id: "135.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "LONGOROKO ",
		healthFacilities: null,
	},
	{
		id: "136.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "KISOP ",
		healthFacilities: null,
	},
	{
		id: "137.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "LOKITUMO ",
		healthFacilities: null,
	},
	{
		id: "138.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "GRAZING AREA",
		healthFacilities: null,
	},
	{
		id: "139.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MOGOTH",
		village: "",
		healthFacilities: null,
	},
	{
		id: "140.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "RUPA",
		village: "NATURUMURUM ",
		healthFacilities: "Rupa HF",
	},
	{
		id: "141.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "RUPA",
		village: "",
		healthFacilities: "Rupa HF",
	},
	{
		id: "142.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "RUPA",
		village: "LORUKUMO ",
		healthFacilities: "Rupa HF",
	},
	{
		id: "143.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "RUPA",
		village: "LOMARIO ",
		healthFacilities: "Rupa HF",
	},
	{
		id: "144.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "RUPA",
		village: "LOKORETE ",
		healthFacilities: "Rupa HF",
	},
	{
		id: "145.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "RUPA",
		village: "ACHOLI INN ",
		healthFacilities: "Rupa HF",
	},
	{
		id: "146.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MUSUPO",
		village: "NAKILORO",
		healthFacilities: "Nakiloro",
	},
	{
		id: "147.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MUSUPO",
		village: "",
		healthFacilities: "Nakiloro",
	},
	{
		id: "148.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MUSUPO",
		village: "APURICHINO ",
		healthFacilities: "Nakiloro",
	},
	{
		id: "149.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MUSUPO",
		village: "LOKWACHOM",
		healthFacilities: "Nakiloro",
	},
	{
		id: "150.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MUSUPO",
		village: "LOMUNYEN-KIRON",
		healthFacilities: "Nakiloro",
	},
	{
		id: "151.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MUSUPO",
		village: "KAILEKOL",
		healthFacilities: "Nakiloro",
	},
	{
		id: "152.0",
		county: "MATHENIKO",
		subCounty: "RUPA",
		parishName: "MUSUPO",
		village: "MUSUPO",
		healthFacilities: "Rupa HF",
	},
	{
		id: "153.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "OLD CHAMPSWAHILI",
		village: "CAMPSWAHILI CHIN ",
		healthFacilities: null,
	},
	{
		id: "154.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "OLD CHAMPSWAHILI",
		village: "KAKOLYE ",
		healthFacilities: null,
	},
	{
		id: "155.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "OLD CHAMPSWAHILI",
		village: "LABOUR LINE",
		healthFacilities: null,
	},
	{
		id: "156.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "OLD CHAMPSWAHILI",
		village: "HOTELS",
		healthFacilities: null,
	},
	{
		id: "157.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "NEW CHAMPSWAHILI",
		village: "NAKAPELIMEN ",
		healthFacilities: "Nmen HF",
	},
	{
		id: "158.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "NEW CHAMPSWAHILI",
		village: "CAMPSWAHILI  JUU ",
		healthFacilities: null,
	},
	{
		id: "159.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "NEW CHAMPSWAHILI",
		village: "REGINA MUNDI",
		healthFacilities: null,
	},
	{
		id: "160.0",
		county: "MUNICIPALITY",
		subCounty: "SOUTH DIVISION",
		parishName: "NEW CHAMPSWAHILI",
		village: "HOTELS",
		healthFacilities: "MRRH",
	},
	{
		id: "161.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA SOUTH",
		village: "JUNIOR QUARTERS",
		healthFacilities: "MRRH",
	},
	{
		id: "162.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA SOUTH",
		village: "HOSPITAL",
		healthFacilities: "MRRH",
	},
	{
		id: "163.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA SOUTH",
		village: "POLICE ",
		healthFacilities: "Police HF",
	},
	{
		id: "164.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA SOUTH",
		village: "SENIOR QUARTERS",
		healthFacilities: "Dmos Clinic HF",
	},
	{
		id: "165.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA SOUTH",
		village: "BAAZAR ",
		healthFacilities: "Dmos Clinic HF",
	},
	{
		id: "166.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA NORTH",
		village: "MOROTO H.S",
		healthFacilities: "Army HF",
	},
	{
		id: "167.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA NORTH",
		village: "RTC",
		healthFacilities: "Dmos Clinic HF",
	},
	{
		id: "168.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA NORTH",
		village: "PRISIONS`",
		healthFacilities: "Prision HF",
	},
	{
		id: "169.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA NORTH",
		village: "ARMY BARACKS",
		healthFacilities: "Army HF",
	},
	{
		id: "170.0",
		county: "MUNICIPALITY",
		subCounty: "NORTH DIVISION",
		parishName: "BOMA NORTH",
		village: "HOTELS",
		healthFacilities: "MRRH",
	},
];
